# Generated by Django 2.2.1 on 2019-06-08 01:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('runtime', models.SmallIntegerField(null=True)),
                ('poster', models.ImageField(upload_to=movies.models.movie_directory_path)),
                ('detail', models.TextField(max_length=150)),
                ('trailer', models.URLField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Historical fiction', 'Historical fiction'), ('Horror', 'Horror'), ('Magical realism', 'Magical realism'), ('Mystery', 'Mystery'), ('Paranoid Fiction', 'Paranoid Fiction'), ('Philosophical', 'Philosophical'), ('Political', 'Political'), ('Romance', 'Romance'), ('Saga', 'Saga'), ('Satire', 'Satire'), ('Science fiction', 'Science fiction'), ('Social', 'Social'), ('Thriller', 'Thriller'), ('Western', 'Western')], default='Action', max_length=40)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('original_language', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['name', 'age'],
            },
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['name', 'age'],
            },
        ),
        migrations.CreateModel(
            name='MovieRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(max_length=150)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_actor',
            field=models.ManyToManyField(to='movies.MovieActor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_director',
            field=models.ManyToManyField(to='movies.MovieDirector'),
        ),
    ]
